# -*- coding: utf-8 -*-
"""Step-7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12BAyaDW_uKbLAU5OIk-jReY02AKLLodP
"""

import numpy as np
import pandas as pd
from statsmodels.graphics.mosaicplot import mosaic
import matplotlib.pyplot as plt

df = pd.read_csv('mcdonalds.csv')
df.head()

df.isna().sum()

df.plot(kind="bar",figsize=(90,20))

crosstable = pd.crosstab(df['Gender'],df['VisitFrequency'])
crosstable

from numpy.core.fromnumeric import size
props = {}
props[('Male','Every three months')] = {'facecolor':'red','edgecolor':'white'}
props[('Male','More than once a week')] = {'facecolor':'red','edgecolor':'white'}
props[('Male','Never')] = {'facecolor':'red','edgecolor':'white'}
props[('Male','Once a month')] = {'facecolor':'red','edgecolor':'white'}
props[('Male','Once a week')] = {'facecolor':'red','edgecolor':'white'}
props[('Male','Once a year')] = {'facecolor':'red','edgecolor':'white'}

props[('Female','Every three months')] = {'facecolor':'blue','edgecolor':'white'}
props[('Female','More than once a week')] = {'facecolor':'blue','edgecolor':'white'}
props[('Female','Never')] = {'facecolor':'blue','edgecolor':'white'}
props[('Female','Once a month')] = {'facecolor':'blue','edgecolor':'white'}
props[('Female','Once a week')] = {'facecolor':'blue','edgecolor':'white'}
props[('Female','Once a year')] = {'facecolor':'blue','edgecolor':'white'}

#plt.figure(figsize=(200,100))
mosaic(df,['Gender','VisitFrequency'],properties=props)

plt.boxplot(df['Age'],notch=None, vert=None, patch_artist=None, widths=None)
plt.boxplot(df['Age'],notch=True, vert=None, patch_artist=None, widths=None)

crosstable1 = pd.crosstab(df['Gender'],df['Age'])
crosstable1

props1={}
props1[('Male','18')] = {'facecolor':'red','edgecolor':'white'}
props1[('Male','19')] = {'facecolor':'red','edgecolor':'white'}
props1[('Male','20')] = {'facecolor':'red','edgecolor':'white'}
props1[('Male','21')] = {'facecolor':'red','edgecolor':'white'}
props1[('Male','22')] = {'facecolor':'red','edgecolor':'white'}
props1[('Male','23')] = {'facecolor':'red','edgecolor':'white'}
props1[('Male','24')] = {'facecolor':'red','edgecolor':'white'}
props1[('Male','25')] = {'facecolor':'red','edgecolor':'white'}


props1[('Female','18')] = {'facecolor':'blue','edgecolor':'white'}
props1[('Female','19')] = {'facecolor':'blue','edgecolor':'white'}
props1[('Female','20')] = {'facecolor':'blue','edgecolor':'white'}
props1[('Female','21')] = {'facecolor':'blue','edgecolor':'white'}
props1[('Female','22')] = {'facecolor':'blue','edgecolor':'white'}
props1[('Female','23')] = {'facecolor':'blue','edgecolor':'white'}
props1[('Female','24')] = {'facecolor':'blue','edgecolor':'white'}
props1[('Female','25')] = {'facecolor':'blue','edgecolor':'white'}

mosaic(df,['Gender','Age'],properties=props1)

